### ISSUE TITLE
Getting Issue with Django==2.1.2 

### ISSUE THREAD

**Issue by itsvks** [jazzband/django-smart-selects#277]
I have followed given documents, However I am getting error while I am trying to load add location page 

Internal Server Error: /admin/api/location/add/
Traceback (most recent call last):
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/utils/html.py", line 397, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/forms/widgets.py", line 58, in __str__
    return self.render()
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/forms/widgets.py", line 61, in render
    return mark_safe('\n'.join(chain.from_iterable(getattr(self, 'render_' + name)() for name in MEDIA_TYPES)))
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/forms/widgets.py", line 61, in <genexpr>
    return mark_safe('\n'.join(chain.from_iterable(getattr(self, 'render_' + name)() for name in MEDIA_TYPES)))
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/forms/widgets.py", line 68, in render_js
    ) for path in self._js
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/forms/widgets.py", line 68, in <listcomp>
    ) for path in self._js
  File "/home/vikas/development/.venv/dependent/lib/python3.6/site-packages/django/forms/widgets.py", line 88, in absolute_path
    if path.startswith(('http://', 'https://', '/')):
AttributeError: 'bool' object has no attribute 'startswith'

**I am facing this issue when I am setting JQUERY_URL = True in settings.py file**

**Comment by abhinavcode** [comment]
Use this USE_DJANGO_JQUERY = True instead of JQUERY_URL = True

**Comment by manelclos** [comment]
Closing old issue, no activity. Please reopen if necessary.
